[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.20"
optimizer = true
optimizer-runs = 1000
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
mantle = "https://rpc.mantle.xyz"
